FROM alpine AS pcov-ext-builder

ARG PCOV_VERSION=v1.0.6

RUN apk -U upgrade && \
    apk add --update --no-cache \
    build-base \
    gcc \
    git \
    linux-headers \
    php7 \
    php7-dev && \
    git clone -b ${PCOV_VERSION} https://github.com/krakjoe/pcov.git && \
    cd pcov && \
    phpize && \
    ./configure --enable-pcov && \
    make && \
    make install && \
    echo -en 'extension=pcov.so\npcov.enabled=1\npcov.directory=app\n' > /etc/php7/conf.d/pcov.ini

FROM frengky/php
LABEL maintainer="frengky.lim@gmail.com"

COPY --from=pcov-ext-builder /usr/lib/php7/modules/pcov.so /usr/lib/php7/modules/
COPY --from=pcov-ext-builder /etc/php7/conf.d/pcov.ini /etc/php7/conf.d/

ENV COMPOSER_ALLOW_SUPERUSER 1
ENV COMPOSER_HOME /tmp

RUN \
    apk --update --no-cache add curl && \
    sed -i "s|memory_limit =.*|memory_limit = -1|i" /etc/php7/php.ini && \
    # https://phpunit.de/index.html
    curl -sSo /usr/local/bin/phpunit "https://phar.phpunit.de/phpunit-latest.phar" && \
    # https://github.com/squizlabs/PHP_CodeSniffer
    curl -sSo /usr/local/bin/phpcs "https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar" && \
    curl -sSo /usr/local/bin/phpcbf "https://squizlabs.github.io/PHP_CodeSniffer/phpcbf.phar" && \
    # https://github.com/FriendsOfPHP/PHP-CS-Fixer
    curl -sSo /usr/local/bin/php-cs-fixer "https://cs.symfony.com/download/php-cs-fixer-v2.phar" && \
    # https://github.com/sensiolabs/security-checker
    curl -sSo /usr/local/bin/security-checker "https://get.sensiolabs.org/security-checker.phar" && \
    # https://github.com/sebastianbergmann/phpcpd
    curl -sSo /usr/local/bin/phpcpd "https://phar.phpunit.de/phpcpd.phar" && \
    # https://github.com/sebastianbergmann/phploc
    curl -sSo /usr/local/bin/phploc "https://phar.phpunit.de/phploc.phar" && \
    # https://phpmd.org/
    curl -sSo /usr/local/bin/phpmd "https://phpmd.org/static/latest/phpmd.phar" && \
    # Set executable bit
    chmod +x \
        /usr/local/bin/phpunit \
        /usr/local/bin/phpcs \
        /usr/local/bin/phpcbf \
        /usr/local/bin/php-cs-fixer \
        /usr/local/bin/security-checker \
        /usr/local/bin/phpcpd \
        /usr/local/bin/phploc \
        /usr/local/bin/phpmd \
        && \
    # Download composer
    curl -sS "https://getcomposer.org/installer" | php -- --install-dir=/usr/local/bin --filename=composer && \
    composer --prefer-dist --no-interaction --no-progress global require \
        # https://github.com/paratestphp/paratest
        'brianium/paratest' \
        # https://www.phpmetrics.org/
        'phpmetrics/phpmetrics' && \
    # Remove composer and curl
    apk del curl && \
    rm -rf /var/cache/apk/*

ENV PATH "$PATH:/tmp/vendor/bin"

WORKDIR /app